# Download base image ubuntu 22.04
#FROM ubuntu:22.04
FROM python:3.9-slim

# author
MAINTAINER Johannes Traa

# extra metadata
LABEL version="0.0.1"
LABEL description="Experiments with Docker - ML model training node"

# Set working dir
WORKDIR /code

# Copy setup files
COPY requirements.txt .
COPY Makefile .

# Install all packages
RUN pip install -r requirements.txt

# Copy Python code
COPY src/docker_exps src/docker_exps

# Define env variables
ENV PYTHONPATH=/code

# Run python process
ENTRYPOINT [ "python3" ]
CMD [ "src/docker_exps/app/app_train.py" ]

