version: '3'

services:
  ml_train:
    image: docker-exps-ml_train
    build:
      context: .
      dockerfile: Dockerfile_train
#    ports:
#      - 48516:48516
    volumes:
      - /home/nuc/docker_exps_home_dir:/home
    environment:
      FLASK_TRAIN_HOST: 0.0.0.0
      FLASK_TRAIN_PORT: 48516
      HOME_DIR: /home
    networks:
      - MLNetwork

networks:
  MLNetwork:
    external: true
